### ISSUE TITLE
everythingStage crashes on mkHsTyWithBndrs:kvs

### ISSUE THREAD

**Issue by rubik** [nominolo/ghc-syb#13]
While traversing the AST with `everythingStaged Parser` GHC 7.8.4 crashes on `mkHsTyWithBndrs`:
```
argon: argon: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
	mkHsTyWithBndrs:kvs

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

As far as I understand, this shouldn't happen, as `everythingStaged` is supposed to avoid known potholes.

Here is how `everythingStaged` is being used:
https://github.com/rubik/argon/blob/master/src/Argon/Visitor.hs

**Comment by rubik** [comment]
Maybe @alanz can help shed light on this? I see he is very knowledgeable about this topic.

**Comment by alanz** [comment]
Can you provide the input file that causes the crash?

**Comment by rubik** [comment]
I'm sorry, I was sure I had included it. Here it is:
```
    {-# LANGUAGE ScopedTypeVariables #-}

    module Utility.Exception where

    import Control.Monad.Catch as X hiding (Handler)
    import qualified Control.Monad.Catch as M

    catchNonAsync :: MonadCatch m => m a -> (SomeException -> m a) -> m a
    catchNonAsync a onerr = a catches
     [ M.Handler ( (e :: SomeException) -> onerr e)
     ]
```

**Comment by alanz** [comment]
It seems it is the `EViewPat` with an enclosed `ExprWithTySig` that is the problem, it uses `mkHsWithBndrs` which initialises with panic values

```haskell
data HsWithBndrs thing
  = HsWB { hswb_cts :: thing         -- Main payload (type or list of types)
         , hswb_kvs :: [Name]        -- Kind vars
         , hswb_tvs :: [Name]        -- Type vars
    }                  
  deriving (Data, Typeable)

mkHsWithBndrs :: thing -> HsWithBndrs thing
mkHsWithBndrs x = HsWB { hswb_cts = x, hswb_kvs = panic "mkHsTyWithBndrs:kvs"
                                     , hswb_tvs = panic "mkHsTyWithBndrs:tvs" }

```

**Comment by alanz** [comment]
@rubik Please try install ghc-syb-utils from my repo to see if my attempt does anything for you.

https://github.com/alanz/ghc-syb

**Comment by rubik** [comment]
Awesome! Thank you for your quick response and fix. It works perfectly now.
Can you upload a new version to Hackage?

**Comment by alanz** [comment]
I will have to put in a pull request, the repo/package belong to @nominolo

**Comment by nominolo** [comment]
Since you have a test program, how hard would it be to add it as a test case? Right now the acceptance criterion is probably just "doesn't crash", but still.

The GHC API is annoyingly unstable and full of those silly potholes. Would be nice to start catching regressions when GHC 8.0 comes along.

**Comment by rubik** [comment]
I can add it very easily to Argon tests. But it's only possible if a new version is pushed to Hackage, because Stack pulls packages from there or from Stackage. I already have quite a few tests that cover multiple cases.

**Comment by rubik** [comment]
CC @nominolo
Unfortunately I found another snippet that exhibits the same issue. While the above code is traversed without errors, this one is not:
```haskell

{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE DefaultSignatures #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}

import Control.Lens.Lens
import Data.Functor.Identity
import Data.Functor.Product
import Data.Proxy (Proxy (Proxy))
import GHC.Generics (Generic (..), (:*:) (..), K1 (..), M1 (..), U1 (..))
import Control.Applicative

type family GSize (f :: * -> *)
type instance GSize U1 = Z
type instance GSize (K1 i c) = S Z
type instance GSize (M1 i c f) = GSize f
type instance GSize (a :*: b) = Add (GSize a) (GSize b)
```

It comes from `Control.Lens.Tuple`. I don't know exactly which extensions besides TypeFamilies are needed so I kept them all. The error remains the same:
```argon: argon: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
	mkHsTyWithBndrs:kvs

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug```

Again, this works with GHC 7.10.2 but not with GHC 7.8.

**Comment by alanz** [comment]
@nominolo I am about to update for the `Coercion` failure, but I see that
the github version of https://github.com/nominolo/ghc-syb does not have any
tests, although there is a target for it in the makefile.

Please clarify what tests you are requesting to be updated


On Fri, Oct 30, 2015 at 10:36 PM, Thomas Schilling <notifications@github.com

**Comment by rubik** [comment]
I think @nominolo was referring to my program Argon. I already added the relevant test cases and confirmed that your changes solve the issues. Now it's just a matter of publishing a new version of ghc-syb-utils.
